name: Actionsflow
on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:
    inputs:
      include:
        description: "--include: workflow file filter"
        required: false
        default: ""
      force:
        description: "--force: whether force to run workflow"
        required: false
        default: "false"
      verbose:
        description: "--verbose: debug workflow"
        required: false
        default: "false"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    concurrency: actionsflow
    steps:
      - uses: actions/checkout@v3
      - name: Debug: Environment Variables
        run: env
      - name: Run Actionsflow
        uses: actionsflow/actionsflow-action@v1.3.0
        with:
          args: "build --include ${{ github.event.inputs.include || ''}} -f ${{github.event.inputs.force=='true' && 'true' || 'false'}} --verbose ${{github.event.inputs.verbose=='true' && 'true' || 'false'}}"
          json-secrets: ${{ toJSON(secrets) }}
          json-github: ${{ toJSON(github) }}
      - name: Setup act
        uses: actionsflow/setup-act-for-actionsflow@v1.2.0
      - name: Run act
        run: act --workflows ./dist/workflows --secret-file ./dist/.secrets --eventpath ./dist/event.json --env-file ./dist/.env -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
